name: CI

on: push

jobs:
  test-app:
    name: testing snapview test task
    runs-on: ubuntu-latest
    steps:
      - name: Getting repo
        uses: actions/checkout@v1

      - name: Setting up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Installing dependencies
        run: npm install

      - name: Executing tests
        run: npm run test:ci
        env:
          CI: true
